로그인 하기
Software-Meister-High-School-Community/MOIZA-iOS pull request #19
Opened 2022-02-13 18:16 UTC by pasin7793

2022-02-13 18:20 UTC, baekteun requested changes

2022-02-13 18:20 UTC, baekteun commented on Target/Source/Application/Flow/Flows/OnBoardingFlow.swift
> +
이상한 공백생김

2022-02-13 18:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Auth/SignIn/Common/View/SignInRegisterLabel.swift
> +
? 얘 뭐임

2022-02-13 18:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Auth/SignIn/Model/SignInOptions.swift
> +}
isOnAutoLogin, isOnIdSave가 reactor에 있어서 필요없을듯

2022-02-13 18:24 UTC, baekteun requested changes

2022-02-13 18:24 UTC, baekteun commented on Target/Source/Presentation/Scene/Auth/SignIn/Reactor/SignInReactor.swift
> +            passwordVisible: false,
passwordTextField isSecureEntry가 기본이 보이는 상태인거 같은데 true로 둬서 기본 상태를 안보이게 두는거 어떰?

2022-02-13 18:27 UTC, baekteun commented
OnBoarding Logo랑 Login Logo에 hero로 애니메이션 주기 어떪?

2022-02-13 18:28 UTC, pasin7793 commented on Target/Source/Presentation/Scene/Auth/SignIn/Common/View/SignInRegisterLabel.swift
> +
저도 이 파일이 안보이는데....

2022-02-13 18:29 UTC, pasin7793 commented on Target/Source/Presentation/Scene/Auth/SignIn/Model/SignInOptions.swift
> +}
이것도 전에 삭제 했는데...

2022-02-13 18:29 UTC, baekteun commented on Target/Source/Presentation/Scene/Auth/SignIn/Common/View/SignInRegisterLabel.swift
> +
ㄴㅇㄱ

2022-02-13 18:30 UTC, baekteun commented on Target/Source/Presentation/Scene/Auth/SignIn/Model/SignInOptions.swift
> +}
어 있는데?

2022-02-13 18:30 UTC, baekteun commented on Target/Source/Presentation/Scene/Auth/SignIn/Model/SignInOptions.swift
> +}
<img width="248" alt="스크린샷 2022-02-14 오전 3 30 22" src="https://user-images.githubusercontent.com/74440939/153769268-5e7eb848-fecd-49e4-ae89-b04c36cf07c3.png">

2022-02-13 18:30 UTC, pasin7793 commented on Target/Source/Presentation/Scene/Auth/SignIn/Reactor/SignInReactor.swift
> +            passwordVisible: false,
수정 완료

2022-02-13 18:31 UTC, baekteun commented on Target/Source/Presentation/Scene/Auth/SignIn/Model/SignInOptions.swift
> +}
make generate 해봐

2022-02-13 18:39 UTC, baekteun commented
Hero, How to think?

2022-02-13 18:39 UTC, baekteun approved these changes

2022-02-14 06:55 UTC, SangAu124 approved these changes
좋아용!! 👍👍

2022-02-14 12:24 UTC, merged