Feat/my page
Software-Meister-High-School-Community/MOIZA-iOS pull request #49
Opened 2022-04-05 14:01 UTC by pasin7793

## 개요
마이페이지 구현(프로필 수정 제외)

## 작업사항
<div>
<img width="150" alt="스크린샷 2022-04-05 오후 10 52 42" src="https://user-images.githubusercontent.com/76590302/161769715-3e061e44-d059-4623-8e80-d3ede83ddfeb.png">
<img src="https://user-images.githubusercontent.com/76590302/161770809-99388c04-0075-4188-9e84-0746aa33f1c2.png" width="150"/>
<img src="https://user-images.githubusercontent.com/76590302/161769732-19d14bf6-82db-4875-8b0b-593233e332e0.png" width="150"/>
<img src="https://user-images.githubusercontent.com/76590302/161769746-10d8e685-1e68-4443-beed-6d306af8f196.png" width="150"/>
</div>

마이페이지, 모달창, 팔로잉, 팔로워 구현

2022-04-05 14:20 UTC, baekteun requested changes

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Application/DI/Container/AppDI.swift
> +
공백제거 Lint

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Application/DI/Container/AppDI.swift
> +
공백 제거

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Domain/Entities/Follow.swift
> +}
이부분 UserListDTO 로 만들자

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Domain/Entities/Follow.swift
> +}
Entity 모델 두고 DTO에서 변환시킬 수 있게ㄲ

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Items/Follower/VC/FollowerVC.swift
> +            .map { _ in Reactor.Action.viewWillAppear }
? viewDidLoad에서 viewWillAppear를 보냄?

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/VC/FollowTabVC.swift
> +        return TMBarItem(title: title)
Reactor의 Follower, Following 수 binding ㄱ

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Modal/VC/MyPageModalVC.swift
> +    private let headerLabel = UILabel().then {
? 이거 왜 만들었어 내가 SortModalVC 쓰라고 했잖어

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Modal/VC/MyPageModalVC.swift
> +    private let headerLabel = UILabel().then {
Reactor에서 steps 에 accept해서 쓰지;;

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/VC/MyPageVC.swift
> +    private lazy var cancel = UIAction(title: "취소", attributes: .destructive, handler: { _ in print("취소") })
// MARK: - MenuAction으로 빼놓는게 나을듯

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/VC/MyPageVC.swift
> +        } else {}
14버전 아래에서는 ActionSheet로 할 수 있게 해주세요

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/View/FollowerCell.swift
> +    private let userId = UILabel().then{
뒤에 Label붙여줘요

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/View/Section/FollowerSection.swift
> +    let header: String
Header는 필요없으니 제거해주세요

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/View/Section/FollowingSection.swift
> +    let header: String
section에 header가 안달렸으니 필요없어보여요 없앱시다

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/PostBoard/Model/PrivacySetting.swift
> +}
공개 설정이 사라졌어요

2022-04-05 14:20 UTC, baekteun commented on Target/Source/Presentation/Utils/Extensions/UIKit/UINavigation/NavigationExt.swift
> +//        print("asdfasdfasdfadf")
Log 지우셈

2022-04-05 14:20 UTC, baekteun commented
git pull origin develop 은 자주 해주세여

2022-04-05 14:24 UTC, baekteun commented
파일구조가
<img width="151" alt="스크린샷 2022-04-05 오후 11 24 00" src="https://user-images.githubusercontent.com/74440939/161775989-d8cec1cf-7534-4110-9626-e36c3817157c.png">

이렇게 되어있는데 MyPage 폴더 안에 MyPage만들어서 VC폴더랑 View 폴더를 넣읍시다 Sub Item이랑 구분하기 위해

2022-04-05 14:26 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/VC/MyPageVC.swift
> +        } else {}
rx.tap으로 바인딩하면 될듯

2022-04-05 14:37 UTC, baekteun commented
https://user-images.githubusercontent.com/74440939/161778612-cfa3fe10-9b0b-41c6-9626-ec436d2795b7.mp4

사파리 갔다가 다시 오면 팔로우, 팔로잉 버튼 위치가 미쳐날뜀

@pasin7793

2022-04-05 14:38 UTC, pasin7793 commented
사실 이거 때문에 레이아웃 잘 봐달라한거임.,..

2022-04-05 14:39 UTC, baekteun commented
<img src="https://user-images.githubusercontent.com/74440939/161778968-03953132-ff4b-4538-8cad-852a9db933b2.png" width="150">

아이폰 13기준 삭제버튼이 좀 잘림

2022-04-06 13:20 UTC, pasin7793 commented on Target/Source/Domain/Entities/Follow.swift
> +}
음 그러면 Follow 따로 UserListDTO 파일 따로 만들까요?

2022-04-06 13:22 UTC, baekteun commented on Target/Source/Domain/Entities/Follow.swift
> +}
네

2022-04-13 11:34 UTC, pasin7793 commented
외부 페이지에 왔다가 오면 이름,팔로워, 팔로잉 등들을 담고 있는 mainContainer uiview의 layout이 이상해지는데 그것만 다시 해도 되지 않을까요?

2022-04-13 13:17 UTC, baekteun commented
만?

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Application/Flow/Flows/Main/Items/MyPageFlow.swift
> +            return coordinateToFollow()
pushViewController로 하니까 coordinateTo 보다는 navigateTo가 더 맞아보여여

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Domain/Entities/UserList.swift
> +import CoreGraphics
unused import

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Domain/Entities/UserList.swift
> +    public let profileImageURL: String
lint 맞춰서 URL이 아닌 Url로 써주세여

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Domain/Entities/UserList.swift
> +    let userScope: UserScope
이 둘이 public이 아니에여

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Domain/Entities/UserList.swift
> +    init(userId: Int, name: String, profileImageURL: String, school: School, userScope: UserScope, isFollow: Bool){
init도 public으로 둬야 접근가능해여

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Items/Follower/VC/FollowerVC.swift
> +        view.backgroundColor = MOIZAAsset.moizaGray1.color
이 친구는 congirueVC에 둬야 함즌ㄴ거같아여

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Reactor/MyPageFollowReactor.swift
> +        var FollowItems: [UserList]
follower랑 following이랑 다르게 State로 둡시다

2022-05-09 03:24 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/PostBoard/Reactor/PostBoardReactor.swift
> +    private let imageURLs: [String] = []
이친구 왜 state에 안뒀는지?

2022-05-09 03:29 UTC, baekteun commented
<img src="https://user-images.githubusercontent.com/74440939/167335738-3c0e9866-d14d-4532-b281-d7d6562cd48b.png" width="150">

스크롤하고나면 팔로잉이 밀려나요

2022-05-09 06:47 UTC, pasin7793 commented on Target/Source/Domain/Entities/UserList.swift
> +    let userScope: UserScope
public을 붙히면 *Property cannot be declared public because its type uses an internal type* 라는 오류가 뜹니다..

2022-05-09 06:48 UTC, baekteun commented on Target/Source/Domain/Entities/UserList.swift
> +    let userScope: UserScope
UserScope랑 School도 public으로 만들면 될거에요

2022-05-09 06:49 UTC, pasin7793 commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Items/Follower/VC/FollowerVC.swift
> +        view.backgroundColor = MOIZAAsset.moizaGray1.color
configureVC() ??

2022-05-09 06:50 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Items/Follower/VC/FollowerVC.swift
> +        view.backgroundColor = MOIZAAsset.moizaGray1.color
ㅇㅇ

2022-05-11 13:52 UTC, baekteun requested changes

2022-05-11 13:52 UTC, baekteun commented on Target/Source/Domain/Entities/FollowerUserList.swift
> +    }
불필요. 제거.

2022-05-11 13:52 UTC, baekteun commented on Target/Source/Domain/Entities/Following.swift
> +        case userList = "user_list"
userList가 있는데 case followingUserList 로 해야됨

2022-05-11 13:52 UTC, baekteun commented on Target/Source/Domain/Entities/FollowingUserList.swift
> +    }
불필요

2022-05-11 13:52 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Items/Follower/VC/FollowerVC.swift
> +        followerListTableView.rx.setDelegate(self).disposed(by: disposeBag)
setDelegate는 setUp에 ㄲ

2022-05-11 13:56 UTC, pasin7793 commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Items/Follower/VC/FollowerVC.swift
> +        followerListTableView.rx.setDelegate(self).disposed(by: disposeBag)
헷갈려서 그러는데 configure랑 setup이랑 어떨 때 쓰죠

2022-05-11 13:58 UTC, baekteun commented on Target/Source/Presentation/Scene/Main/Items/MyPage/Follow/Items/Follower/VC/FollowerVC.swift
> +        followerListTableView.rx.setDelegate(self).disposed(by: disposeBag)
setUp은 delegate같은 작업, configureVC는 view.background같은, VC에서만 하는 UX

2022-07-09 09:24 UTC, merged